get http://127.0.0.1:3000

# ###
# post http://127.0.0.1:3000

###
get http://127.0.0.1:3000/api/v1/tours?fields=-summary,-description

###
get http://127.0.0.1:3000/api/v1/tours?maxGroupSize=gt:14,lt:21&duration=gte:7,lte:9&sort=maxGroupSize&fields=-summary,-description

###
get http://127.0.0.1:3000/api/v1/tours/5c88fa8cf4afda39709c296c

###
POST http://127.0.0.1:3000/api/v1/tours
Content-Type: application/json

{
  "name": "The Forest Hiker",
  "duration": 5,
  "maxGroupSize": 25,
  "difficulty": "easy",
  "ratingsAverage": 4.7,
  "ratingsQuantity": 37,
  "price": 397,
  "maxGrupSize": 6,
  "summary": "Breathtaking hike through the Canadian Banff National Park",
  "description": "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "imageCover": "tour-1-cover.jpg",
  "images": ["tour-1-1.jpg", "tour-1-2.jpg", "tour-1-3.jpg"],
  "startDates": ["2021-04-25,10:00", "2021-07-20,10:00", "2021-10-05,10:00"]
}

### UPDATE TOUR
PATCH  http://127.0.0.1:3000/api/v1/tours/64f589405d0768bb98618236
Content-Type: application/json

{  
  "startDates": ["2021-04-25,10:00", "2021-07-20,10:00", "2021-10-05,10:00"]
}

### DELETE TOUR
DELETE  http://127.0.0.1:3000/api/v1/tours/64f4a58bf923c4ae08191106


####################################
### USERS


###
get http://127.0.0.1:3000/api/v1/users

###
get http://127.0.0.1:3000/api/v1/users/21

###
get http://127.0.0.1:3000/api/v1/users/5c8a1d5b0190b214360dc057

###
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "name": "abc",
  "email" : "abc@g.com",
  "role" : "member"
}

### UPDATE TOUR
PATCH  http://127.0.0.1:3000/api/v1/users/21
Content-Type: application/json

{
  "active" : true,
  "email" : "abc@gi.com"
}

### DELETE TOUR
DELETE  http://127.0.0.1:3000/api/v1/users/21