get http://127.0.0.1:3000

# ###
# post http://127.0.0.1:3000

###
get http://127.0.0.1:3000/api/v1/tours

###
get http://127.0.0.1:3000/api/v1/tours/A64f3cd5db7edfa66c9c31f52

###
POST http://127.0.0.1:3000/api/v1/tours
Content-Type: application/json

{
  "name": "A Food Eater",
  "duration" : 5,
  "difficulty" : "easy",
  "price" : 200
}

### UPDATE TOUR
PATCH  http://127.0.0.1:3000/api/v1/tours/64f3cd5db7edfa66c9c31f52
Content-Type: application/json

{
  "price": 250
}

### DELETE TOUR
DELETE  http://127.0.0.1:3000/api/v1/tours/64f3daec29fc0a4246aa2b33


####################################
### USERS


###
get http://127.0.0.1:3000/api/v1/users

###
get http://127.0.0.1:3000/api/v1/users/21

###
get http://127.0.0.1:3000/api/v1/users/5c8a1d5b0190b214360dc057

###
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "name": "abc",
  "email" : "abc@g.com",
  "role" : "member"
}

### UPDATE TOUR
PATCH  http://127.0.0.1:3000/api/v1/users/21
Content-Type: application/json

{
  "active" : true,
  "email" : "abc@gi.com"
}

### DELETE TOUR
DELETE  http://127.0.0.1:3000/api/v1/users/21