
###
get http://127.0.0.1:3000/api/v1/users

###
get http://127.0.0.1:3000/api/v1/users/65290eb038d25dfd8f219155

### CREATE USER
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "name": "asd",
  "email" : "asd@g.com",
  "photo": "2.jpg",
  "password": "asd"
}

### SIGNUP
POST http://127.0.0.1:3000/api/v1/users/signup
Content-Type: application/json

{
  "name": "asd",
  "email" : "asd@g.com",
  "photo": "asd.jpg",
  "password": "asd"
}

### SIGNIN
POST http://127.0.0.1:3000/api/v1/users/signin
Content-Type: application/json

{
  "name": "asd",
  "password": "asd"
}

### UPDATE
PATCH  http://127.0.0.1:3000/api/v1/users/65290a6960a89f67683ffcf9
Content-Type: application/json

{  
  "email" : "abc@ccccom"
}

### DELETE
DELETE  http://127.0.0.1:3000/api/v1/users/65290a6960a89f67683ffcf9