@url = http://{{hostname}}:{{port}}/api/{{version}}/users

###
get {{url}}
Authorization: Bearer {{token}}

###
get {{url}}/65290eb038d25dfd8f219155


### SIGNUP User
POST {{url}}/signup
Content-Type: application/json

{
  "name": "asd",
  "email" : "asd@g.com",
  "photo": "asd.jpg",
  "password": "asd"
}

### SIGNUP Admin
POST {{url}}/signup
Content-Type: application/json

{
  "name": "admin",
  "email" : "admin@g.com",
  "role" : "admin",
  "photo": "admin.jpg",
  "password": "admin"
}

### LOGIN
# @name LOGIN
POST {{url}}/login
Content-Type: application/json

{
  "email": "asd@g.com",
  "password": "asd"
}

### // Get token from (named) request: LOGIN
@token = {{LOGIN.response.body.$.token}}

### VERIFY JWT

POST {{url}}/verifyjwt
Content-Type: application/json
Authorization: Bearer {{token}}

{

}

### VERIFY JWT ERROR
POST {{url}}/verifyjwt
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MmZkYTExMzg5MzgzNDI1N2RlN2U0ZiIsImlhdCI6MTY5ODA3Mzk0MCwiZXhwIjoxNzA1ODQ5OTQwfQ.2EpuJKx9undutdIGlIfZpR4C-O7tIKRgEIUiEGA5g5k

{

}

### UPDATE USER
PATCH  {{url}}/652fda113893834257de7e4f
Content-Type: application/json

{  
  "password" : "asd"
}

### DELETE USER
DELETE  {{url}}/6538e216d3c3b4fdf6e7a82c